### ISSUE TITLE
Conflict with vscodevim

### ISSUE THREAD

**Issue by PCanyi** [michaelgriscom/LeaderMode#31] opened 2019-03-19 10:31 UTC
When I use vscodevim, I found that use "ctrl+;" had tips in status bar, but could not do the next step.

**Comment by michaelgriscom** [comment] 2019-03-19 10:40
Thanks for reporting! `Ctrl+;` is probably a bad default, I'll try to push out a version with a better default today

In the meantime you can set the shortcut for `leadermode.enter` to something else inside your keybindings.json file

**Comment by michaelgriscom** [comment] 2019-03-19 10:43
Ah just re-read and saw you're using vscodevim, as mentioned in the Known Issues vscodevim doesn't play well with other extensions that use keystroke commands, the issue is tracked [here](https://github.com/Microsoft/vscode/issues/13441)

I'll close this one out for now since there's nothing that can be done within this extension to fix it. Sorry about that

**Closed by michaelgriscom** 2019-03-19 10:43 UTC
